name: Create issues across prods

on:
  push:
  
jobs: 
  create-new-issue:
    strategy:
      matrix:
        prod: [prod1, prod2]
     
    uses: rndrepos/common/.github/workflows/create-issue-via-gh.yml@main
    secrets: inherit
    with:
      title: "${{ matrix.prod}} issue"
      body: "Update for a level"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: echo ${{ needs.create-new-issue.outputs.issue-number }}
