name: Repo Info with context

on:
  workflow_call:

jobs:
  info:
  
    runs-on: ubuntu-latest

    steps:
            
      - uses: actions/checkout@v3
          
      - name: Show repo info
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo Repository is ${{ github.repository }}
          echo "::debug::Debugging is turned on for steps and runner"
          echo Size of local repository area is `du -hs ${{ github.workspace }}`
          echo Context dump follows:
          echo "$GITHUB_CONTEXT"
